// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/backent/ai-golang/controllers/controllers_auth"
	"github.com/backent/ai-golang/controllers/controllers_question"
	"github.com/backent/ai-golang/libs"
	"github.com/backent/ai-golang/repositories/repositories_auth"
	"github.com/backent/ai-golang/repositories/repositories_question"
	"github.com/backent/ai-golang/repositories/repositories_storage"
	"github.com/backent/ai-golang/services/services_ai"
	"github.com/backent/ai-golang/services/services_auth"
	"github.com/backent/ai-golang/services/services_question"
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
)

// Injectors from injector.go:

func InitializeRouter() *httprouter.Router {
	repositoryAuthInterface := repositories_auth.NewRepositoryAuthJWTImpl()
	serviceAuthInterface := services_auth.NewServiceAuthImplementation(repositoryAuthInterface)
	authControllerInterface := controllers_auth.NewAuthControllerImplementation(serviceAuthInterface, repositoryAuthInterface)
	aiServiceInterface := services_ai.NewAiServiceGemini()
	storageServiceInterface := repositories_storage.NewStorageServiceLocalImplementation()
	repositoryQuestionInterface := repositories_question.NewRepositoryQuestionImplementation()
	db := libs.NewDatabase()
	questionServiceInterface := services_question.NewQuestionServiceImplementation(aiServiceInterface, storageServiceInterface, repositoryQuestionInterface, db)
	questionControllerInterface := controllers_question.NewQuestionControllerImplementation(questionServiceInterface, repositoryAuthInterface)
	router := libs.NewRouter(authControllerInterface, questionControllerInterface)
	return router
}

// injector.go:

var AuthSet = wire.NewSet(controllers_auth.NewAuthControllerImplementation, services_auth.NewServiceAuthImplementation, repositories_auth.NewRepositoryAuthJWTImpl)

var QuestionSet = wire.NewSet(controllers_question.NewQuestionControllerImplementation, services_question.NewQuestionServiceImplementation, repositories_question.NewRepositoryQuestionImplementation)

var AiSet = wire.NewSet(services_ai.NewAiServiceGemini)

var RepositoriesSet = wire.NewSet(repositories_storage.NewStorageServiceLocalImplementation)
