CREATE TABLE questions (
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  name VARCHAR(190) NOT NULL,
  amount INT NOT NULL,
  gemini_file_uri VARCHAR(100) NOT NULL,
  file_name VARCHAR(100) NOT NULL,
  result TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
)